In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
x, y = make_regression(n_samples = 100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [4]:
x

array([[ 6.58840199e-01,  3.52017439e-02],
       [-9.73196643e-02,  3.75857607e-01],
       [ 6.03479110e-01,  6.64456295e-01],
       [-9.62720465e-01, -1.15001184e+00],
       [-3.68760528e-01,  3.58419455e-01],
       [ 6.19836291e-01, -1.06346449e+00],
       [ 1.32943060e+00, -1.13708631e-01],
       [ 1.04234874e+00,  1.95933424e+00],
       [-8.44669883e-01,  2.11378752e-01],
       [-3.24513537e-01,  8.21094403e-01],
       [ 7.85376809e-02, -1.67344521e+00],
       [-5.67705954e-01,  2.47844051e-01],
       [ 8.68676552e-01, -4.73912750e-01],
       [ 1.73495388e+00, -2.60646482e-01],
       [-8.48859618e-01, -3.34855788e-01],
       [ 4.51227871e-01, -2.47717641e-01],
       [ 2.47541892e-01,  1.01216405e+00],
       [-1.52407055e+00,  5.06057229e-02],
       [-1.73227674e+00, -4.20272294e-03],
       [-1.59487148e-01, -1.20506291e+00],
       [-1.00316085e+00, -2.97094031e+00],
       [ 2.09957836e+00, -1.23687549e-01],
       [-5.37893869e-01, -1.43991307e+00],
       [-2.

In [5]:
y

array([ 102.07844023,   99.18257532,   65.90816326,  -88.10276411,
        100.5612529 ,   74.10188298,  122.36188546,  177.9832017 ,
       -119.80922196,  -85.15853157,  -17.08895201,  -70.33321324,
        133.76818164,  123.97322456, -129.09145043,   51.16392242,
         55.08626219, -148.69935265, -175.29713996,   31.53854289,
       -235.11453417,  192.65714158,  -63.62096008,  -66.94546599,
       -137.76344444,   38.17926658,   47.36541088,   -2.02368648,
        159.03137744,  -13.08600793,  128.82584898,  106.9584907 ,
       -184.82139667,   53.71637385,  130.78749867,  195.85144829,
        125.87420298,  -47.48964903,   46.52819915,   58.32357763,
         -4.519394  ,   29.36593722, -207.00088635,   -1.4402607 ,
         47.59951534,   40.95082688,  138.95638574,  -50.47013476,
        -32.08962768,    9.55247431,   16.08243978,   72.11091583,
         70.2386835 ,   -1.9813555 , -109.97485179,   14.26257332,
       -225.01899797,  -38.7612069 ,   40.18539309,  -47.61365

In [6]:
df = pd.DataFrame({'feature1':x[:,0], 'feature2':x[:,1], 'target':y})

In [8]:
df.head()

feature1  feature2      target
0  0.658840  0.035202  102.078440
1 -0.097320  0.375858   99.182575
2  0.603479  0.664456   65.908163
3 -0.962720 -1.150012  -88.102764
4 -0.368761  0.358419  100.561253

In [9]:
df.shape

(100, 3)

In [11]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

In [13]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

In [14]:
print("MAE", mean_absolute_error(y_test, y_pred))
print("MSE", mean_squared_error(y_test, y_pred))
print("R2 Score", r2_score(y_test, y_pred))

MAE 37.34975693997013
MSE 1978.5663165956878
R2 Score 0.8624837309256715


In [17]:
import plotly.graph_objects as go
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

z = z_final



In [18]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [19]:
lr.coef_

array([96.23656186, 34.8839119 ])

In [20]:
lr.intercept_

5.2596809361314465